# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c1902088049ca854244af0590618c4815874264c8b8280a9416953ad86ec7afd838424f56d6213a090ecd41162f01c8b63d6a361a5a3f0d10dbec4658a529ad

test:
  secret_key_base: ac75b0d2cf377a86ee3bd0244516d19182cbd8e914438d8ded3adf7ff89cd57d395c1f04188878410db7bb2f1e59f4f2ec442cdcd78cad7523d9b4356859a485

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
